# https://github.com/codeSTACKr/codeSTACKr/blob/master/.github/workflows/blog-post-workflow.yml
# https://www.youtube.com/watch?v=ECuqb5Tv9qI
# https://github.com/gautamkrishnar/blog-post-workflow
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@thibault-friedrich'
